dataset:
  name: MicroDoppler
  dim_x: 12288
  shape: [3, 64, 64]

model:
  name: DiffusersGaussianSQVAE
  param_var_q: gaussian_3
  log_param_q_init: 2.995732273553991

quantization:
  dim_dict: 64
  size_dict: 512
  temperature:
    init: 1.0
    decay: 0.00001
    min: 0.0

train:
  seed: 0
  bs: 32
  lr: 0.001
  epoch_max: 100

test:
  bs: 50

flags:
  save: True
  arelbo: True
  bn: True
  decay: True
  var_q: True
  noprint: False

network:
  name: diffusers
  encoder:
    block_out_channels: [128, 256, 512]
    down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
    layers_per_block: 2
  decoder:
    block_out_channels: [512, 256, 128]
    up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
    layers_per_block: 2

nworker: 4
processing:
  method: downsample

path: /kaggle/working/outputs
path_specific: microdoppler_diffusers_sqvae_gaussian_3/
path_dataset: /kaggle/input/dataset

list_dir_for_copy: ['', 'networks/'] 