training:
    batch_size: 52
    sample_frames: 32
    sigma_sq: 1e0
    n_steps: 500000
    optimizer:
        lr: 4e-4
    scheduler:
        milestones:
            - 300000
            - 400000
        gamma: 0.5
    temperature:
        init: 1.0
        decay: 1e-5
    checkpoint_interval: 20000
    n_workers: 8
