path_specific: "microdoppler_sqvae_gaussian_1_64x64_enhanced_v2/"

dataset:
  name: 'MicroDoppler'  # 使用专门的MicroDoppler配置
  shape: (3, 64, 64)
  dim_x: 12288 # 3 * 64 * 64
  num_users: 31
  root_path: "/kaggle/input/dataset"

model:
  name: "GaussianSQVAE"
  log_param_q_init: 2.995732273553991  # log(20.0)
  param_var_q: "gaussian_1"

network:
  name: "resnet"  # 使用64×64架构
  num_rb: 10  # 增加ResBlock：提升时频特征提取能力

train:
  bs: 16  # 64×64分辨率
  lr: 0.0001  # 稍高学习率：加快收敛
  epoch_max: 150  # 更长训练：充分学习时频特征

flags:
  arelbo: True
  bn: True
  decay: True
  noprint: True
  save: True
  var_q: False

quantization:
  size_dict: 128   # 更小codebook：提高利用率
  dim_dict: 64     # 保持维度
  temperature:
    init: 1.0      
    decay: 0.000002  # 更慢衰减：让模型充分学习
    min: 0.3       # 更高最小温度：保持多样性
